import Link from "next/link";
import { loadAnalytics, requireAnalyticsAccess, passRateOf, avgScoreOf, riskBuckets } from "@/lib/analytics";
import { OUTCOME_CONFIG, type DecisionOutcome } from "@/lib/ckcm";
import { StatTiles, Card } from "../../reports/ui";
import { AiHeader } from "../ui";
import AskAi from "../AskAi";

// Learner Intelligence — 360° per-learner view with an AI development plan
// generated by the existing coach engine (grounded in the learner's real
// decision gaps and linked learning resources).

export const dynamic = "force-dynamic";
type SearchParams = Promise<{ n?: string }>;

export default async function LearnerIntelligencePage({ searchParams }: { searchParams: SearchParams }) {
  const { admin, hospitalId } = await requireAnalyticsAccess();
  const ctx = await loadAnalytics(admin, hospitalId);
  const { n } = await searchParams;
  const risk = riskBuckets(ctx.latest, ctx.nurses.length);

  const sel = n ? ctx.nurses.find(x => x.id === n) ?? null : null;
  const mineDecisions = sel ? ctx.latest.filter(d => d.nurse_id === sel.id) : [];
  const mineAssess = sel ? ctx.assess.filter(a => a.nurse_id === sel.id) : [];
  const mineEntries = sel ? ctx.entries.filter(e => e.nurse_id === sel.id) : [];
  const { data: recentDecRaw } = sel
    ? await admin.from("competency_decisions")
        .select("outcome, created_at, expiry_date, framework_competencies!competency_id(name)")
        .eq("nurse_id", sel.id).order("created_at", { ascending: false }).limit(6)
    : { data: [] };

  return (
    <div className="max-w-4xl">
      <AiHeader icon="🧬" title="Learner Intelligence" sub="360° intelligence on learner performance — real records plus an AI development plan on demand." />

      <div className="bg-white border border-gray-200 rounded-xl p-3 mb-4 flex items-center gap-2 flex-wrap">
        <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Learner</span>
        <form action="/assessor/ai/learner" className="flex items-center gap-2">
          <select name="n" defaultValue={sel?.id ?? ""}
            className="text-xs border border-gray-200 rounded-lg px-2 py-1.5 bg-white text-gray-700 focus:outline-none focus:border-indigo-400">
            <option value="">Choose a learner…</option>
            {ctx.nurses.map(x => <option key={x.id} value={x.id}>{x.name} · {x.dept}</option>)}
          </select>
          <button type="submit" className="text-xs font-semibold text-white bg-indigo-600 rounded-lg px-3 py-1.5 hover:bg-indigo-700">Open</button>
        </form>
        {sel && <Link href={`/assessor/passports?n=${sel.id}`} className="text-[11px] font-semibold text-indigo-600 hover:underline ml-auto">Passport →</Link>}
      </div>

      {sel ? (
        <>
          <StatTiles tiles={[
            { label: "Overall Risk", value: (risk.byNurse.get(sel.id) ?? "low").toUpperCase(), alert: risk.byNurse.get(sel.id) === "high", sub: "from decision records" },
            { label: "Competencies Decided", value: String(mineDecisions.length), sub: `${mineDecisions.filter(d => d.passing && !d.expired).length} currently passing` },
            { label: "Assessments (8w)", value: String(mineAssess.length), sub: `pass ${passRateOf(mineAssess) ?? "—"}% · avg ${avgScoreOf(mineAssess) ?? "—"}` },
            { label: "Evidence", value: String(mineEntries.length), sub: `${mineEntries.filter(e => e.status === "pending").length} pending`, },
          ]} />

          <div className="grid md:grid-cols-2 gap-4 mb-4">
            <Card title="Recent Decisions">
              {(recentDecRaw ?? []).length ? (recentDecRaw ?? []).map((d, i) => {
                const oc = OUTCOME_CONFIG[d.outcome as DecisionOutcome];
                return (
                  <div key={i} className="flex items-center gap-2 text-[11px] py-1">
                    <span className="text-gray-700 flex-1 truncate">{(d.framework_competencies as unknown as { name: string } | null)?.name ?? "—"}</span>
                    <span className="text-gray-300" suppressHydrationWarning>{new Date(d.created_at).toLocaleDateString()}</span>
                    <span className={`text-[9px] font-bold px-1.5 py-0.5 rounded ${oc?.cls ?? "bg-gray-100 text-gray-600"}`}>{oc?.label ?? d.outcome}</span>
                  </div>
                );
              }) : <p className="text-xs text-gray-400">No decisions on record.</p>}
            </Card>
            <Card title="AI Development Plan" sub="coach engine — grounded in this learner's real gaps + linked resources">
              <AskAi endpoint="/api/ai/coach" body={{ nurse_id: sel.id }} label={`Generate plan for ${sel.name.split(" ")[0]}`} />
            </Card>
          </div>

          <p className="text-[10px] text-gray-400">
            Full drill-down (evidence timeline, feedback, sessions) lives in the{" "}
            <Link href="/assessor/nurses" className="text-indigo-500 hover:underline">Learners workspace</Link>. Competency radar charts need per-domain
            score history and are not simulated.
          </p>
        </>
      ) : (
        <div className="bg-white border border-gray-200 rounded-xl p-10 text-center">
          <p className="text-3xl mb-2">🧬</p>
          <p className="text-sm text-gray-500">Choose a learner to see their intelligence profile and generate an AI development plan.</p>
        </div>
      )}
    </div>
  );
}
