// The public site's canonical origin, and the one list of what is actually indexable.
//
// WHY THIS EXISTS. LP-PRA-001 and LP-BOOK-001 both list SEO as an acceptance criterion ("SEO-ready",
// "SEO-friendly public pages") and none of it was there: no sitemap, no canonical URLs, and no Open Graph
// tags anywhere in the application. The last one matters more than it sounds for a product sold in East
// Africa -- a Competen Practice link shared into a WhatsApp group renders as a bare URL rather than a card
// with a title, a description and a picture, and a bare URL in a group chat is a link nobody taps.
//
// THE INDEXABLE LIST IS DERIVED, NOT TYPED OUT. It is built from the same catalogues as the routes
// themselves, so a new solution, capability page or journey appears in the sitemap by existing. A
// hand-maintained sitemap is stale within two commits and nothing ever fails because of it.

import { SOLUTIONS } from "./solutions";
import { PRACTICE_AREAS } from "./practice-content";
import { JOURNEYS } from "./practice-site";

/**
 * Production origin, overridable per deployment. No trailing slash.
 *
 * The default is the live site rather than localhost: metadataBase is what turns a relative Open Graph
 * image path into an absolute URL, and if it silently fell back to localhost in production every social
 * card would point at a machine nobody else can reach -- which fails invisibly, because the page itself
 * looks perfect.
 */
export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.competenhealthcare.com")
  .replace(/\/+$/, "");

export const abs = (path: string) => `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;

export type IndexablePage = { path: string; priority: number; changeFrequency: "weekly" | "monthly" };

/**
 * Every page that should appear in the sitemap.
 *
 * NOT INCLUDED, deliberately:
 *   /verify/<token>   the token IS the access control; indexing it would put a named clinician's
 *                     competency record into search results. robots.ts disallows it for the same reason.
 *   /forgot-password  transactional, and useless as a search result
 *   /reset-password   token-driven; there is nothing at the bare URL to index
 *   every authenticated workspace -- see the AUTHENTICATED list in robots.ts
 *
 * /login and /signup ARE included: people genuinely search for "competen login", and a sitemap entry is
 * how that resolves to the right page rather than to whatever a search engine guesses.
 */
export function indexablePages(): IndexablePage[] {
  return [
    { path: "/", priority: 1.0, changeFrequency: "weekly" },

    // The solution landing pages, from the catalogue that also defines their routes.
    // ⚠ /hospitals left this list when the catalogue renamed the pathway to /organisations (WEB-HOME-001
    // s20, 2026-08-11) -- the route still exists as a permanent redirect, and a sitemap must name the
    // canonical page, not the redirect that reaches it.
    ...SOLUTIONS.map(s => ({ path: `/${s.slug}`, priority: 0.9, changeFrequency: "monthly" as const })),

    // The not-yet-live Individual product page (WEB-HOME-001 s10) -- a marketing page with an honest
    // CTA, indexed because it describes a real offering. ⚠ /recruitment is NOT repeated here: the
    // Recruiters catalogue entry above already emits it, and a sitemap with the same URL twice is the
    // kind of defect a validator reports and a person never notices.
    { path: "/individual", priority: 0.9, changeFrequency: "monthly" },

    // Competen Practice: its four journeys carry higher priority than the capability detail, because they
    // are what a visitor is actually trying to reach.
    ...JOURNEYS.map(j => ({ path: j.href, priority: 0.8, changeFrequency: "monthly" as const })),
    ...PRACTICE_AREAS.map(a => ({ path: `/practice/${a.slug}`, priority: 0.7, changeFrequency: "monthly" as const })),

    { path: "/login", priority: 0.5, changeFrequency: "monthly" },
    { path: "/signup", priority: 0.5, changeFrequency: "monthly" },
  ];
}

/** Default social card. Generated by scripts/build-og-images.mjs; see that file for the sizing rules. */
export const DEFAULT_OG_IMAGE = "/images/og/competen.jpg";
export const OG_IMAGE_SIZE = { width: 1200, height: 630 };

/**
 * Build a public page's metadata: title, description, canonical, Open Graph and Twitter, all consistent
 * with each other.
 *
 * THIS EXISTS BECAUSE TWO THINGS DO NOT INHERIT THE WAY THEY LOOK LIKE THEY DO.
 *
 * 1. CANONICAL. A canonical URL set in the root layout is inherited by every page, so every page declares
 *    itself a copy of the homepage -- which asks a search engine not to index any of them separately. That
 *    is worse than having no canonical at all, and it would quietly cancel out the sitemap. A canonical
 *    must be the page's OWN url or absent; there is no useful middle.
 *
 * 2. OPEN GRAPH. Next merges `openGraph` as a block, not field by field. A page that sets `title` and
 *    `description` but no `openGraph` keeps the PARENT's og:title and og:description -- so the page reads
 *    correctly in a search result and unfurls in WhatsApp as the generic site card. The failure is
 *    invisible from the page itself, which is why it survives.
 *
 * Passing through one function means a page cannot get one of these right and the other wrong.
 */
export function pageMetadata(opts: {
  title: string;
  description: string;
  /** Site-relative, e.g. "/practice/book". */
  path: string;
  /** Site-relative image; defaults to the site-wide card. */
  image?: string;
  imageAlt?: string;
}) {
  const image = opts.image ?? DEFAULT_OG_IMAGE;
  const alt = opts.imageAlt ?? "Competen";
  return {
    title: opts.title,
    description: opts.description,
    alternates: { canonical: opts.path },
    openGraph: {
      type: "website" as const,
      siteName: "Competen",
      locale: "en_GB",
      url: abs(opts.path),
      title: opts.title,
      description: opts.description,
      images: [{ ...OG_IMAGE_SIZE, url: image, alt }],
    },
    twitter: {
      card: "summary_large_image" as const,
      title: opts.title,
      description: opts.description,
      images: [image],
    },
  };
}
