"use client";
import { useEffect, useState } from "react";

// CMO-017 live copilot — calls /api/competency/copilot which runs the real AI Runtime Gateway (generate()) grounded
// in live competency data. Every call logs to plat_ai_requests → appears in the AI Services Platform observability.
const PROMPTS = [
  "Give me a competency risk briefing",
  "Which certifications need attention this month?",
  "Summarise our readiness gaps and top 3 actions",
  "What are the highest-priority accreditation gaps?",
];

export default function CmoCopilot() {
  const [configured, setConfigured] = useState<boolean | null>(null);
  const [q, setQ] = useState("");
  const [answer, setAnswer] = useState<string | null>(null);
  const [meta, setMeta] = useState<{ model?: string; grounded?: number } | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch("/api/competency/copilot").then(r => r.json()).then(d => setConfigured(!!d.configured)).catch(() => setConfigured(false));
  }, []);

  async function ask(question?: string) {
    const text = (question ?? q).trim();
    setLoading(true); setError(null); setAnswer(null); setMeta(null);
    try {
      const res = await fetch("/api/competency/copilot", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question: text || undefined }) });
      const data = await res.json();
      if (!res.ok) { setError(data.error ?? "Copilot error."); return; }
      setAnswer(data.answer); setMeta({ model: data.model, grounded: data.grounded });
    } catch { setError("Network error — could not reach the copilot."); }
    finally { setLoading(false); }
  }

  return (
    <div className="bg-gradient-to-br from-violet-50 to-teal-50 border border-violet-100 rounded-xl p-4">
      <div className="flex items-center gap-2 mb-2">
        <span className="w-7 h-7 rounded-lg bg-violet-600 text-white flex items-center justify-center text-sm">🤖</span>
        <div className="flex-1"><p className="text-sm font-semibold text-gray-900">Competency Copilot</p><p className="text-[11px] text-gray-500">Live AI over your competency data · routed through the AI Services Platform</p></div>
        {configured === false && <span className="text-[10px] font-semibold text-amber-700 bg-amber-100 rounded px-1.5 py-0.5">AI not configured</span>}
        {configured === true && <span className="text-[10px] font-semibold text-emerald-700 bg-emerald-100 rounded px-1.5 py-0.5">● Live</span>}
      </div>

      <div className="flex gap-2">
        <input value={q} onChange={e => setQ(e.target.value)} onKeyDown={e => { if (e.key === "Enter" && !loading) ask(); }} placeholder="Ask about competency risk, readiness, certifications, gaps…" className="flex-1 border border-gray-200 rounded-lg px-3 py-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-violet-500/20" disabled={loading || configured === false} />
        <button onClick={() => ask()} disabled={loading || configured === false} className="px-4 py-2 rounded-lg bg-violet-600 text-white text-sm font-medium hover:bg-violet-500 disabled:opacity-50 disabled:cursor-not-allowed">{loading ? "Thinking…" : "Ask"}</button>
      </div>

      <div className="flex flex-wrap gap-1.5 mt-2">
        {PROMPTS.map(p => <button key={p} onClick={() => { setQ(p); ask(p); }} disabled={loading || configured === false} className="text-[11px] text-violet-700 bg-white border border-violet-100 rounded-full px-2.5 py-1 hover:bg-violet-50 disabled:opacity-50">{p}</button>)}
      </div>

      {error && <div className="mt-3 text-[12px] text-amber-800 bg-amber-50 border border-amber-200 rounded-lg p-2.5">{error}{configured === false ? " The seeded recommendations below remain available." : ""}</div>}
      {answer && (
        <div className="mt-3 bg-white border border-gray-200 rounded-lg p-3">
          <p className="text-[13px] text-gray-800 whitespace-pre-wrap leading-relaxed">{answer}</p>
          {meta && <p className="text-[10px] text-gray-400 mt-2 pt-2 border-t border-gray-100">Generated by {meta.model} · grounded in {meta.grounded} live data signals · logged to the AI gateway.</p>}
        </div>
      )}
    </div>
  );
}
