"use client";

import { useState } from "react";

// Reusable "generate with AI" block: posts to a grounded AI endpoint and
// renders the answer with the standard provenance caption. Used by the
// insights/competency/risk/simulation/learner/report modules.

export default function AskAi({ endpoint, body, label, doneLabel }: {
  endpoint: string; body: Record<string, unknown>; label: string; doneLabel?: string;
}) {
  const [busy, setBusy] = useState(false);
  const [text, setText] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function go() {
    setBusy(true); setError(null);
    const res = await fetch(endpoint, {
      method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body),
    });
    const d = await res.json().catch(() => ({}));
    if (res.ok && d.answer) setText(d.answer);
    else setError(d.error ?? "AI request failed");
    setBusy(false);
  }

  return (
    <div>
      <button onClick={go} disabled={busy}
        className="no-print text-xs font-bold text-white bg-indigo-600 rounded-lg px-4 py-2 hover:bg-indigo-700 disabled:opacity-50 transition-colors">
        {busy ? "Thinking…" : text ? `↻ ${doneLabel ?? "Regenerate"}` : `✨ ${label}`}
      </button>
      {error && <p className="text-xs text-red-600 mt-2">{error}</p>}
      {text && (
        <div className="mt-3 bg-indigo-50/60 border border-indigo-100 rounded-lg p-3.5">
          <p className="text-xs text-gray-700 whitespace-pre-wrap leading-relaxed">{text}</p>
          <p className="text-[8px] text-gray-400 mt-2">Generated by Claude from live platform figures — advisory only; decisions remain with the assessor. Logged in the AI audit trail.</p>
        </div>
      )}
    </div>
  );
}
