// AI Quality Intelligence Centre (UMG-QS-011) — the AI layer over the Quality & Safety domain. Composes the live
// clinical-indicator and M&M stores and derives: an enterprise AI quality-risk index, a PREDICTIVE engine (linear
// trend forecasts per indicator + mortality/morbidity rate, with breach prediction + confidence from trend fit),
// emerging-risk detection, ROOT-CAUSE intelligence (from the real M&M contributory factors + causes of death),
// and a prioritised, EXPLAINABLE recommendation engine (each with evidence / impact / effort / confidence). The
// natural-language executive brief is generated by the Claude model when configured, with a rule-based fallback.
// Real, explainable, human-in-the-loop. True ML model governance/drift (§13/§14) is honest next-phase.
/* eslint-disable @typescript-eslint/no-explicit-any */
import { loadClinicalIndicators } from "@/lib/operations/clinical-indicators";
import { loadMortalityMorbidity } from "@/lib/operations/mortality-morbidity";
import { generate } from "@/lib/ai/client";

// Linear-regression forecast of the next point + a confidence from the fit (R²) + breach test.
function forecast(series: number[], target: number | null, direction: string) {
  const s = series.filter(v => v != null && Number.isFinite(v));
  if (s.length < 3) return null;
  const n = s.length, meanX = (n - 1) / 2, meanY = s.reduce((a, b) => a + b, 0) / n;
  let num = 0, den = 0; for (let i = 0; i < n; i++) { num += (i - meanX) * (s[i] - meanY); den += (i - meanX) ** 2; }
  const slope = den ? num / den : 0; const next = s[n - 1] + slope;
  const yhat = (i: number) => meanY + slope * (i - meanX);
  let ssr = 0, sst = 0; for (let i = 0; i < n; i++) { ssr += (s[i] - yhat(i)) ** 2; sst += (s[i] - meanY) ** 2; }
  const r2 = sst ? Math.max(0, 1 - ssr / sst) : 0;
  const confidence = Math.round(Math.max(45, Math.min(94, 50 + r2 * 45)));
  const dir = slope > 0.02 ? "up" : slope < -0.02 ? "down" : "flat";
  const breach = target != null && (direction === "lower_is_better" ? next > target : next < target);
  return { next: Math.round(next * 100) / 100, dir, breach, confidence };
}

export async function loadAiQualityIntelligence(admin: any, hid: string | null, isSuper: boolean) {
  const [ind, mm] = await Promise.all([
    loadClinicalIndicators(admin, hid, isSuper).catch(() => null) as Promise<any>,
    loadMortalityMorbidity(admin, hid, isSuper).catch(() => null) as Promise<any>,
  ]);
  const indReady = ind?.provisioned && ind?.hasData;
  const mmReady = mm?.provisioned && mm?.hasData;
  if (!indReady && !mmReady) return { provisioned: false as const };

  // ── Predictive engine — forecast each measured indicator + the M&M rates ──────────────────────
  const predictions: any[] = [];
  if (indReady) {
    for (const i of ind.indicators) {
      const series = (ind.trend.periods as string[]).map((p: string) => i.byPeriod?.[p]).filter((v: any) => v != null).map(Number);
      const f = forecast(series, i.target, i.direction);
      if (f && (f.breach || f.dir !== "flat")) predictions.push({ name: i.name, category: i.category?.replace(/ Indicators$/, ""), current: i.value, forecast: f.next, unit: i.unit, dir: f.dir, breach: f.breach, confidence: f.confidence, target: i.target, kind: "indicator" });
    }
  }
  if (mmReady && mm.trend?.periods?.length >= 3) {
    const mF = forecast(mm.trend.mortality, null, "lower_is_better");
    const bF = forecast(mm.trend.morbidity, null, "lower_is_better");
    if (mF) predictions.push({ name: "Mortality Rate", category: "Outcome", current: mm.kpis.mortalityRate, forecast: mF.next, unit: "rate_per_1000", dir: mF.dir, breach: mF.dir === "up", confidence: mF.confidence, kind: "rate" });
    if (bF) predictions.push({ name: "Morbidity Rate", category: "Outcome", current: mm.kpis.morbidityRate, forecast: bF.next, unit: "rate_per_1000", dir: bF.dir, breach: bF.dir === "up", confidence: bF.confidence, kind: "rate" });
  }
  predictions.sort((a, b) => (b.breach ? 1 : 0) - (a.breach ? 1 : 0) || b.confidence - a.confidence);
  const predictedBreaches = predictions.filter(p => p.breach);

  // ── Enterprise AI quality-risk index (0–100; higher = more risk) ──────────────────────────────
  const indRisk = indReady && ind.kpis.overallScore != null ? 100 - ind.kpis.overallScore : null;
  const mmRisk = mmReady ? Math.round(mm.kpis.aiRisk * 100) : null;
  const breachRisk = predictions.length ? Math.round((predictedBreaches.length / predictions.length) * 100) : null;
  const parts = [indRisk, mmRisk, breachRisk].filter((x): x is number => x != null);
  const aiRiskIndex = parts.length ? Math.round(parts.reduce((a, b) => a + b, 0) / parts.length) : null;
  const forecastAccuracy = predictions.length ? Math.round(predictions.reduce((a, b) => a + b.confidence, 0) / predictions.length) : null;

  // ── Emerging risks — worsening + below-target signals ─────────────────────────────────────────
  const emerging: any[] = [];
  if (indReady) ind.indicators.filter((i: any) => i.worsening && i.status !== "green").slice(0, 4).forEach((i: any) => emerging.push({ signal: `${i.name} declining`, detail: `${i.value}${i.unit === "percent" ? "%" : ""} and worsening — ${i.category?.replace(/ Indicators$/, "")}`, severity: i.status === "red" ? "high" : "medium" }));
  if (mmReady && mm.kpis.preventablePct >= 20) emerging.push({ signal: "Preventable-death signal", detail: `${mm.kpis.preventablePct}% of deaths assessed preventable this period`, severity: "high" });

  // ── Root-cause intelligence — probable contributing factors (M&M factors + causes of death) ────
  const rootCauses = (mmReady ? (mm.contributoryFactors ?? []) : []).map((f: any) => ({ factor: f.label, weight: f.pct, n: f.n }));
  const causePatterns = (mmReady ? (mm.topCauses ?? []) : []).slice(0, 4).map((c: any) => ({ label: c.label, pct: c.pct }));

  // ── Recommendation engine — prioritised, explainable ──────────────────────────────────────────
  const recommendations: any[] = [];
  if (indReady) ind.topUnderperformers.slice(0, 3).forEach((i: any) => recommendations.push({
    action: `${i.direction === "lower_is_better" ? "Reduce" : "Improve"} ${i.name}`, category: i.category?.replace(/ Indicators$/, ""),
    evidence: `Currently ${i.value}${i.unit === "percent" ? "%" : ""} vs ${i.target}${i.unit === "percent" ? "%" : ""} target (${i.status})`,
    impact: i.status === "red" ? "High" : "Medium", effort: "Medium", confidence: 78 + (i.status === "red" ? 8 : 0),
  }));
  if (mmReady && rootCauses[0]) recommendations.push({ action: `Strengthen ${rootCauses[0].factor.toLowerCase()} pathways`, category: "Mortality & Morbidity", evidence: `Top contributory factor in ${rootCauses[0].weight}% of reviewed cases`, impact: "High", effort: "Medium", confidence: 82 });
  const breachRec = predictedBreaches[0];
  if (breachRec) recommendations.push({ action: `Pre-empt forecast breach in ${breachRec.name}`, category: breachRec.category, evidence: `Predicted ${breachRec.forecast}${breachRec.unit === "percent" ? "%" : ""} next period (${breachRec.confidence}% confidence)`, impact: "High", effort: "Low", confidence: breachRec.confidence });
  recommendations.sort((a, b) => (a.impact === "High" ? 0 : 1) - (b.impact === "High" ? 0 : 1) || b.confidence - a.confidence);

  // ── Natural-language executive brief — Claude when configured, rule-based fallback ────────────
  const facts = [
    aiRiskIndex != null ? `AI quality-risk index ${aiRiskIndex}/100` : null,
    indReady ? `clinical attainment ${ind.kpis.overallScore}%, ${ind.kpis.atEscalation} indicators at escalation` : null,
    mmReady ? `mortality ${mm.kpis.mortalityRate}/1000, ${mm.kpis.preventableDeaths} preventable deaths (${mm.kpis.preventablePct}%)` : null,
    predictedBreaches.length ? `${predictedBreaches.length} metric(s) predicted to breach: ${predictedBreaches.slice(0, 3).map(p => p.name).join(", ")}` : null,
    rootCauses[0] ? `leading contributory factor: ${rootCauses[0].factor} (${rootCauses[0].weight}%)` : null,
  ].filter(Boolean).join("; ");
  let narrative: string; let narrativeSource: "ai" | "rule" = "rule";
  const gen = await generate({ system: "You are a hospital quality intelligence analyst. In 3–4 concise sentences, write an executive brief from the supplied live quality metrics: state the overall risk posture, the most important trend or predicted breach, the leading root cause, and the single highest-priority action. Reference specific numbers. No preamble.", user: facts || "No metrics available.", tier: "reasoning", maxTokens: 320, context: { operation: "quality_intelligence" } }).catch(() => null);
  if (gen?.ok && gen.text.trim()) { narrative = gen.text.trim(); narrativeSource = "ai"; }
  else narrative = `Enterprise AI quality-risk index is ${aiRiskIndex ?? "—"}/100${aiRiskIndex != null ? (aiRiskIndex >= 40 ? " (elevated)" : " (contained)") : ""}. ${predictedBreaches.length ? `${predictedBreaches.length} metric(s) are trending toward a threshold breach, led by ${predictedBreaches[0].name}.` : "No metrics are forecast to breach next period."} ${rootCauses[0] ? `The leading contributory factor across reviewed cases is ${rootCauses[0].factor} (${rootCauses[0].weight}%).` : ""} ${recommendations[0] ? `Highest-priority action: ${recommendations[0].action.toLowerCase()}.` : ""}`.replace(/\s+/g, " ").trim();

  return {
    provisioned: true as const,
    aiRiskIndex, forecastAccuracy,
    kpis: {
      aiRiskIndex, predictedBreaches: predictedBreaches.length, recommendations: recommendations.length,
      forecastConfidence: forecastAccuracy, emergingRisks: emerging.length,
      dataSources: [indReady && "Clinical Indicators", mmReady && "Mortality & Morbidity"].filter(Boolean).length,
    },
    narrative, narrativeSource,
    predictions: predictions.slice(0, 10), emerging, rootCauses, causePatterns, recommendations: recommendations.slice(0, 6),
  };
}
