import { requireAnalyticsAccess, loadAnalytics } from "@/lib/analytics";
import { AiHeader } from "../ui";
import ReportWriterClient from "./ReportWriterClient";

// AI Report Writer — professional narrative reports generated by Claude from
// figures the server computes for the chosen window/department. Export via
// print-to-PDF; every generation is audit-logged.

export const dynamic = "force-dynamic";

export default async function ReportWriterPage() {
  const { admin, hospitalId } = await requireAnalyticsAccess();
  const ctx = await loadAnalytics(admin, hospitalId);
  const departments = [...new Set(ctx.nurses.map(n => n.dept))].sort();

  const { data: recent } = await admin.from("audit_log")
    .select("actor_name, new_value, created_at")
    .eq("action", "ai_report").order("created_at", { ascending: false }).limit(6);

  return (
    <div className="max-w-4xl">
      <AiHeader icon="📝" title="AI Report Writer" sub="Generate professional governance reports instantly — Claude writes the narrative, the platform supplies the figures." />
      <ReportWriterClient
        departments={departments}
        recent={(recent ?? []).map(r => ({
          who: r.actor_name ?? "—",
          type: (r.new_value as { report_type?: string } | null)?.report_type ?? "report",
          at: r.created_at,
        }))}
      />
      <p className="text-[10px] text-gray-400 mt-4">
        Reports are generated fresh from live figures and are not stored — use ⬇ PDF (print) or copy the text into your document system.
        The model receives only computed figures and cannot introduce numbers of its own.
      </p>
    </div>
  );
}
