"use client";

import { useState } from "react";

// AI Studio generators — real Claude generation grounded in governed
// competency content. Assessment/scenario generators take a name + optional
// competency; the advisor summarises the live competency profile. Every call
// is quota-limited and audit-logged server-side.

type Comp = { id: string; name: string };

function Generator({ endpoint, nameKey, nameLabel, cta, competencies }: {
  endpoint: string; nameKey: string; nameLabel: string; cta: string; competencies: Comp[];
}) {
  const [name, setName] = useState("");
  const [comp, setComp] = useState("");
  const [busy, setBusy] = useState(false);
  const [text, setText] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function go() {
    if (!name.trim()) { setError("Give it a name first."); return; }
    setBusy(true); setError(null);
    const res = await fetch(endpoint, {
      method: "POST", headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ [nameKey]: name, competency_id: comp || undefined }),
    });
    const d = await res.json().catch(() => ({}));
    if (res.ok && d.answer) setText(d.answer);
    else setError(d.error ?? "AI request failed");
    setBusy(false);
  }

  return (
    <div>
      <div className="flex items-center gap-2 flex-wrap mb-2">
        <input value={name} onChange={e => setName(e.target.value)} placeholder={nameLabel}
          className="flex-1 min-w-[180px] text-xs border border-gray-200 rounded-lg px-2.5 py-2 focus:outline-none focus:border-purple-400" />
        <select value={comp} onChange={e => setComp(e.target.value)}
          className="text-xs border border-gray-200 rounded-lg px-2 py-2 bg-white text-gray-600 focus:outline-none focus:border-purple-400 max-w-[240px]">
          <option value="">Ground in competency (optional)…</option>
          {competencies.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
        </select>
        <button onClick={go} disabled={busy}
          className="text-xs font-bold text-white bg-purple-600 rounded-lg px-4 py-2 hover:bg-purple-700 disabled:opacity-50 transition-colors">
          {busy ? "Thinking…" : `✨ ${cta}`}
        </button>
      </div>
      {error && <p className="text-xs text-red-600">{error}</p>}
      {text && (
        <div className="bg-purple-50/60 border border-purple-100 rounded-lg p-3">
          <p className="text-xs text-gray-700 whitespace-pre-wrap leading-relaxed max-h-72 overflow-y-auto">{text}</p>
          <p className="text-[8px] text-gray-400 mt-2">Generated by Claude from governed content — review and edit before use. Audit-logged.</p>
        </div>
      )}
    </div>
  );
}

export function AssessmentGenerator({ competencies }: { competencies: Comp[] }) {
  return <Generator endpoint="/api/ai/osce" nameKey="station_name" nameLabel="OSCE station name (e.g. IV cannulation)" cta="Generate station" competencies={competencies} />;
}
export function ScenarioGenerator({ competencies }: { competencies: Comp[] }) {
  return <Generator endpoint="/api/ai/simulation" nameKey="scenario_name" nameLabel="Scenario name (e.g. Deteriorating post-op patient)" cta="Generate scenario" competencies={competencies} />;
}

export function AdvisorGenerator() {
  const [busy, setBusy] = useState(false);
  const [text, setText] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  async function go() {
    setBusy(true); setError(null);
    const res = await fetch("/api/ai/insights", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ scope: "competency" }) });
    const d = await res.json().catch(() => ({}));
    if (res.ok && d.answer) setText(d.answer); else setError(d.error ?? "AI request failed");
    setBusy(false);
  }
  return (
    <div>
      <button onClick={go} disabled={busy}
        className="text-xs font-bold text-white bg-purple-600 rounded-lg px-4 py-2 hover:bg-purple-700 disabled:opacity-50 transition-colors mb-2">
        {busy ? "Analysing…" : "✨ Analyse curriculum & competency coverage"}
      </button>
      {error && <p className="text-xs text-red-600">{error}</p>}
      {text && (
        <div className="bg-purple-50/60 border border-purple-100 rounded-lg p-3">
          <p className="text-xs text-gray-700 whitespace-pre-wrap leading-relaxed">{text}</p>
          <p className="text-[8px] text-gray-400 mt-2">Generated by Claude from live competency figures — advisory only. Audit-logged.</p>
        </div>
      )}
    </div>
  );
}
