/**
 * CPR-DOC-002 Documents Workspace harness -- PHASE 2 (s20): the structured editor, PDF render, the
 * SIGNATURE and Shared & Issued. Exercised against the live database through the same engines the pages
 * and the API use.
 *
 * WHAT IT PROVES:
 *   1.  s7.1 -- SIGNING A DOCUMENT IS NOT SIGNING AN ENCOUNTER. Two seeded capability codes, two tables,
 *       and a live fixture where signing the document leaves the consultation untouched -- with the
 *       control that signing the CONSULTATION does move it, so the first is not an inert fixture. The
 *       attestation reaches the trail carrying its wording, its version and the SHA-256 of the text
 *       signed, and the digest is checked against a recomputation AND against a different document's.
 *   2.  s17 -- A SIGNED DOCUMENT IS IMMUTABLE, AND IT IS THE DATABASE THAT SAYS SO. The refusal is
 *       migration 195's trigger, identified by its own message, with the identical raw update on a DRAFT
 *       succeeding as the control.
 *   3.  s17 -- A PATIENT-SPECIFIC DOCUMENT CANNOT BE ISSUED WITHOUT A PATIENT LINK. Refused at the sign
 *       AND at the issue, over a document whose patient belongs to another practice, with the same
 *       operation on a correctly linked document succeeding.
 *   4.  s13 -- AN ASSISTANT MAY AUTHOR AND MAY ISSUE, AND MAY NOT SIGN. Migration 248's boundary, probed
 *       live against the seeded catalogue and then exercised through a real assistant context.
 *   5.  s12/s8 -- AN UNRESOLVED MERGE FIELD BLOCKS THE SIGNATURE, end to end: generated by
 *       document-generation.ts, refused by signDocument(), and signed once removed.
 *   6.  s8 -- THE EDITOR PAYLOAD IS PLAIN DATA, walked to its leaves for functions, with a positive
 *       control that the walker really finds one.
 *   7.  s3 -- SHARED & ISSUED, including the one thing nothing else in this product can answer: who is
 *       holding a copy of a version that has since been amended.
 *   8.  s6.4 -- RECIPIENT RULES: emailed refuses without an address, printed warns, and the warning is
 *       absent when a recipient is given.
 *   9.  s17 -- ONLY A SIGNED DOCUMENT MAY BE ISSUED, and never a superseded one.
 *   10. THE CLIENT/SERVER BOUNDARY, statically: the editor component imports nothing that reaches the
 *       Supabase server client. A server-only import crossing into a client component compiles, lints and
 *       passes every runtime harness, and then the page is dead.
 *
 * CONTROLS: every refusal is paired with the same operation succeeding where it should, so a green
 * "refused" can never be an artefact of a malformed call.
 *
 *   npx --yes tsx scripts/practice-documents-phase2-harness.ts
 */
import { existsSync, readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { join } from "node:path";
import { loadEnvConfig } from "@next/env";
import { createClient } from "@supabase/supabase-js";
import { runProvisioning, type IndividualRequest } from "../src/lib/practice/provisioning";
import { registerPatient } from "../src/lib/practice/patients";
import { resolveWorkspaceContext, hasCapability, type WorkspaceContext } from "../src/lib/practice/access";
import {
  createDocument, transitionDocument, amendDocument, createTemplate, setTemplateStatus,
} from "../src/lib/practice/documentation";
import { launchEncounter, transitionEncounter } from "../src/lib/practice/encounters";
import { generateFromTemplate } from "../src/lib/practice/document-generation";
import {
  signDocument, issueDocument, editorSupport, sharedAndIssued, bodyDigest,
} from "../src/lib/practice/documents-workspace-issue";
import {
  DOC_ATTESTATION, DOC_TABS, RECIPIENT_REQUIRED_CHANNELS, SHARE_DELIVERY_NOTE,
  unresolvedMarkers, signBlockers,
} from "../src/lib/practice/documents-workspace-constants";
import { RELEASE_CHANNELS } from "../src/lib/practice/document-constants";
import { purgeWorkspacesOwnedBy } from "./_cleanup";

loadEnvConfig(process.cwd());

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) { console.error("Supabase env not set"); process.exit(1); }
const admin = createClient(url, key, { auth: { persistSession: false } });

const USER_A = "00000000-0000-4000-8000-00000000d2a1";
const USER_B = "00000000-0000-4000-8000-00000000d2a2";
const ASSISTANT = "00000000-0000-4000-8000-00000000d2a3";

let pass = 0;
const fails: string[] = [];
const ok = (label: string, cond: boolean, detail = "") => {
  if (cond) { pass++; console.log(`  PASS  ${label}`); }
  else { fails.push(label); console.log(`  FAIL  ${label}${detail ? ` -- ${detail}` : ""}`); }
};

/* eslint-disable @typescript-eslint/no-explicit-any */

const CID = "harness-docp2";

const payload = (name: string): IndividualRequest => ({
  displayName: name, countryCode: "UG", timezone: "Africa/Kampala", professionCode: "medical_doctor",
  defaultPracticeType: "clinic", locale: "en-UG", termsVersion: "t1", privacyNoticeVersion: "p1", source: "pilot",
});

async function provision(user: string, name: string, suffix: string): Promise<string> {
  const { data: req } = await admin.from("provisioning_request").insert({
    idempotency_key: `harness-docp2-${suffix}`, request_type: "pilot",
    actor_user_id: user, target_user_id: user, payload_hash: "harness", correlation_id: CID,
  }).select("id").single();
  const run = await runProvisioning(admin, {
    id: req!.id, target_user_id: user, correlation_id: CID, workspace_id: null,
  }, payload(name));
  if (!run.ok || !run.workspaceId) throw new Error(`provisioning failed: ${run.errorCode}`);
  return run.workspaceId;
}

async function cleanup() {
  await purgeWorkspacesOwnedBy(admin, [USER_A, USER_B, ASSISTANT]);
}

const base = { actorId: USER_A, correlationId: CID };

async function newPatient(workspaceId: string, name: string, phone: string, opts: {
  birthDate?: string; ageEstimateYears?: number;
} = {}): Promise<string> {
  const r = await registerPatient(admin, {
    workspaceId, displayName: name, sex: "female", phone,
    birthDate: opts.birthDate, ageEstimateYears: opts.ageEstimateYears,
    actorId: USER_A, correlationId: CID,
  } as any);
  if (!r.ok) throw new Error(`registerPatient failed: ${(r as any).message}`);
  return r.data.id;
}

/** Create -> FINAL -> SIGNED through the LOW-LEVEL engine, for fixtures that must already be signed. */
async function forceSigned(workspaceId: string, documentId: string) {
  await transitionDocument(admin, { workspaceId, documentId, to: "FINAL", ...base });
  await transitionDocument(admin, { workspaceId, documentId, to: "SIGNED", ...base });
}

/**
 * ⚠ WALK EVERY LEAF OF A PAYLOAD LOOKING FOR A FUNCTION.
 *
 * A function on an object handed to a client component compiles, lints, passes the API and every runtime
 * harness, and then the page white-screens in a production build. It killed the Follow-ups board this
 * week. `typeof payload === "object"` at the top level does not find it; this does.
 */
function functionPaths(value: unknown, path = "$", seen = new Set<unknown>()): string[] {
  if (typeof value === "function") return [path];
  if (value === null || typeof value !== "object") return [];
  if (seen.has(value)) return [];
  seen.add(value);
  const found: string[] = [];
  if (Array.isArray(value)) {
    value.forEach((v, i) => found.push(...functionPaths(v, `${path}[${i}]`, seen)));
    return found;
  }
  for (const [k, v] of Object.entries(value as Record<string, unknown>))
    found.push(...functionPaths(v, `${path}.${k}`, seen));
  return found;
}

async function main() {
  console.log("\nCPR-DOC-002 Documents Workspace harness (Phase 2 -- s20: editor, render, signature, sharing)\n");
  await cleanup();

  const wsA = await provision(USER_A, "Harness Phase2 A", "a");
  const wsB = await provision(USER_B, "Harness Phase2 B", "b");

  const pAlice = await newPatient(wsA, "HARNESS Alice Nakato", "+256700900001", { birthDate: "1990-04-02" });
  // ⚠ NO BIRTH DATE, ON PURPOSE. This patient is what makes assertion 6 non-vacuous: one field in the
  // SAME merge payload must resolve and another must not, so "resolved" cannot be a constant.
  const pNoDob = await newPatient(wsA, "HARNESS Grace Apio", "+256700900002", { ageEstimateYears: 41 });
  const pOther = await newPatient(wsB, "HARNESS Other Practice", "+256700900003", { birthDate: "1988-01-09" });

  const aCtxRes = await resolveWorkspaceContext(admin, USER_A, wsA);
  if (!aCtxRes.ok) { ok("setup. the practitioner context resolves", false, (aCtxRes as any).reason); return report(); }
  const aCtx: WorkspaceContext = aCtxRes.ctx;
  ok("setup-control. the practitioner context holds document.sign, document.author and document.view",
    hasCapability(aCtx, "document.sign") && hasCapability(aCtx, "document.author") && hasCapability(aCtx, "document.view"),
    JSON.stringify(aCtx.capabilities.filter(c => c.startsWith("document"))));

  /* ══ 1. s7.1 -- SIGNING A DOCUMENT IS NOT SIGNING AN ENCOUNTER ═════════════════════════════════ */

  const { data: seeded, error: seedError } = await admin.from("practice_role_capabilities")
    .select("role_code, capability_code");
  const seedRows = (seeded ?? []) as any[];
  ok("1a-control. practice_role_capabilities was read (every code check below would pass vacuously on an empty table)",
    !seedError && seedRows.length > 0, seedError?.message ?? `${seedRows.length} rows`);
  const seedSet = new Set(seedRows.map(r => r.capability_code as string));
  const NAMED = ["document.view", "document.author", "document.sign", "encounter.sign", "encounter.edit", "template.manage"];
  const invented = NAMED.filter(c => !seedSet.has(c));
  ok("1a. every capability code Phase 2 names exists in the live catalogue -- none invented",
    invented.length === 0, invented.length ? `INVENTED: ${invented.join(", ")}` : `${seedSet.size} distinct codes seeded`);
  ok("1b. ⚠ document.sign and encounter.sign are TWO DIFFERENT SEEDED CODES, which is s7.1 in the permission model",
    seedSet.has("document.sign") && seedSet.has("encounter.sign"), "one of the two is missing");

  // A real consultation, and a document written from it. Signing the document must not touch it.
  const enc = await launchEncounter(admin, {
    workspaceId: wsA, patientId: pAlice, pathway: "new_walk_in",
    reasonForVisit: "HARNESS: cough", actorId: USER_A, correlationId: CID,
  });
  if (!enc.ok) { ok("1-setup. an encounter for the s7.1 fixture", false, (enc as any).message); return report(); }
  const encId = (enc as any).data.id as string;
  // DRAFT -> ACTIVE -> COMPLETED. ⚠ THE FIRST STEP WAS MISSING AND 1c-control-2 CAUGHT IT: the encounter
  // sat at DRAFT, which cannot become SIGNED, so the control read as red exactly as it should -- 1c was
  // passing over a fixture that could not have moved either way.
  const toActive = await transitionEncounter(admin, { workspaceId: wsA, encounterId: encId, to: "ACTIVE", ...base });
  const toCompleted = await transitionEncounter(admin, { workspaceId: wsA, encounterId: encId, to: "COMPLETED", ...base });
  ok("1-setup-2. the consultation really reached COMPLETED, so it is one step from its own signature",
    toActive.ok && toCompleted.ok,
    `${toActive.ok ? "ok" : (toActive as any).code} / ${toCompleted.ok ? "ok" : (toCompleted as any).code}`);

  const letter = await createDocument(admin, {
    workspaceId: wsA, patientId: pAlice, encounterId: encId, docType: "referral_letter",
    title: "HARNESS referral from the consultation", body: "Please see this patient for a cough.", ...base,
  });
  if (!letter.ok) { ok("1-setup. a document on that encounter", false, (letter as any).message); return report(); }
  const letterId = letter.data.id;

  const { data: encBefore } = await admin.from("practice_encounter")
    .select("status, signed_at, signed_by").eq("id", encId).single();

  await transitionDocument(admin, { workspaceId: wsA, documentId: letterId, to: "FINAL", ...base });
  const signedLetter = await signDocument(admin, aCtx, {
    documentId: letterId, attestationVersion: DOC_ATTESTATION.version, correlationId: CID,
  });
  ok("1c-control. the document signs cleanly, so everything below is about a signature that happened",
    signedLetter.ok, signedLetter.ok ? "" : `${(signedLetter as any).code}: ${(signedLetter as any).message}`);

  const { data: encAfter } = await admin.from("practice_encounter")
    .select("status, signed_at, signed_by").eq("id", encId).single();
  ok("1c. ⚠ signing the DOCUMENT left the consultation exactly as it was -- status, signed_at and signed_by all unmoved",
    encAfter?.status === encBefore?.status && encAfter?.signed_at === null && encAfter?.signed_by === null,
    `${JSON.stringify(encBefore)} -> ${JSON.stringify(encAfter)}`);

  await transitionEncounter(admin, { workspaceId: wsA, encounterId: encId, to: "SIGNED", ...base });
  const { data: encSigned } = await admin.from("practice_encounter")
    .select("status, signed_at, signed_by").eq("id", encId).single();
  ok("1c-control-2. ...and the encounter's OWN signature DOES move those columns, so 1c is not an inert fixture",
    encSigned?.status === "SIGNED" && !!encSigned?.signed_at && encSigned?.signed_by === USER_A,
    JSON.stringify(encSigned));

  const { data: attestations } = await admin.from("practice_audit_event")
    .select("payload, event_type").eq("workspace_id", wsA).eq("event_type", "practice.document_attested");
  const att = ((attestations ?? []) as any[]).find(e => e.payload?.documentId === letterId);
  ok("1d. the attestation reaches the trail as its own event, naming the act, the wording and the version",
    !!att && att.payload?.act === "document"
    && att.payload?.attestationVersion === DOC_ATTESTATION.version
    && att.payload?.statement === DOC_ATTESTATION.statement,
    JSON.stringify(att?.payload));

  const { data: signedRow } = await admin.from("practice_clinical_document")
    .select("body, signed_at, signed_by, status").eq("id", letterId).single();
  const recomputed = createHash("sha256").update(String(signedRow?.body ?? ""), "utf8").digest("hex");
  ok("1e. the digest in the attestation is the SHA-256 of the text the record actually holds",
    att?.payload?.bodySha256 === recomputed && typeof recomputed === "string" && recomputed.length === 64,
    `${att?.payload?.bodySha256} vs ${recomputed}`);
  ok("1e-control. ...and it is NOT the digest of a different body, so 1e is not comparing a constant to itself",
    att?.payload?.bodySha256 !== bodyDigest("Please see this patient for a rash."),
    "the digest did not move with the text");
  ok("1f. and the signature itself is on the document row: signed_at, signed_by, status SIGNED",
    !!signedRow?.signed_at && signedRow?.signed_by === USER_A && signedRow?.status === "SIGNED",
    JSON.stringify(signedRow && { ...signedRow, body: undefined }));

  // The attestation version is echoed back by the caller. Stale wording cannot produce a signature.
  const staleDoc = await createDocument(admin, {
    workspaceId: wsA, patientId: pAlice, title: "HARNESS stale attestation", body: "Body.", ...base,
  });
  await transitionDocument(admin, { workspaceId: wsA, documentId: (staleDoc as any).data.id, to: "FINAL", ...base });
  const stale = await signDocument(admin, aCtx, {
    documentId: (staleDoc as any).data.id, attestationVersion: "doc-0-from-an-older-deploy", correlationId: CID,
  });
  ok("1g. ⚠ a signature offered against WORDING THAT IS NO LONGER ON THE SCREEN is refused",
    !stale.ok && (stale as any).code === "ATTESTATION_STALE",
    stale.ok ? "was allowed" : (stale as any).code);
  const staleFixed = await signDocument(admin, aCtx, {
    documentId: (staleDoc as any).data.id, attestationVersion: DOC_ATTESTATION.version, correlationId: CID,
  });
  ok("1g-control. the identical call carrying the CURRENT version succeeds, so 1g is the version and not the document",
    staleFixed.ok, staleFixed.ok ? "" : (staleFixed as any).code);

  /* ══ 2. s17 -- A SIGNED DOCUMENT IS IMMUTABLE, BY THE DATABASE ═════════════════════════════════ */

  const rawEdit = await admin.from("practice_clinical_document")
    .update({ body: "REWRITTEN BY A RAW STATEMENT" }).eq("id", letterId).select("id");
  ok("2a. ⚠ a RAW update of a signed document's body -- no engine involved -- is refused",
    !!rawEdit.error, rawEdit.error?.message ?? "WAS ALLOWED: the guarantee is engine-only");
  ok("2b. ⚠ and the refusal is MIGRATION 195's TRIGGER speaking, not an application check reimplemented here",
    /is signed; it can only be amended into a new version/.test(rawEdit.error?.message ?? ""),
    rawEdit.error?.message ?? "(no error at all)");

  const draftForRaw = await createDocument(admin, {
    workspaceId: wsA, patientId: pAlice, title: "HARNESS still a draft", body: "Draft body.", ...base,
  });
  const rawDraftEdit = await admin.from("practice_clinical_document")
    .update({ body: "REWRITTEN, LEGITIMATELY" }).eq("id", (draftForRaw as any).data.id).select("id");
  ok("2a-control. the IDENTICAL raw update on a DRAFT succeeds, so 2a is the signature and not the syntax",
    !rawDraftEdit.error && (rawDraftEdit.data ?? []).length === 1,
    rawDraftEdit.error?.message ?? `${(rawDraftEdit.data ?? []).length} rows`);

  const { data: stillSigned } = await admin.from("practice_clinical_document")
    .select("body").eq("id", letterId).single();
  ok("2c. and the signed text is byte-for-byte what was hashed at the signature",
    bodyDigest(String(stillSigned?.body ?? "")) === att?.payload?.bodySha256,
    `${bodyDigest(String(stillSigned?.body ?? ""))} vs ${att?.payload?.bodySha256}`);

  /* ══ 3. s17 -- NO PATIENT LINK, NO ISSUE ═══════════════════════════════════════════════════════ */

  // The schema's own half of the rule.
  const rawNoPatient = await admin.from("practice_clinical_document")
    .insert({ workspace_id: wsA, patient_id: null, title: "HARNESS no patient", body: "x" }).select("id");
  ok("3a. a document with NO patient cannot exist at all -- the column is NOT NULL (migration 195 s4)",
    !!rawNoPatient.error, rawNoPatient.error?.message ?? "WAS ALLOWED");
  const rawWithPatient = await admin.from("practice_clinical_document")
    .insert({ workspace_id: wsA, patient_id: pAlice, title: "HARNESS with patient", body: "x" }).select("id");
  ok("3a-control. the IDENTICAL insert WITH a patient succeeds, so 3a is the link and not the statement",
    !rawWithPatient.error && (rawWithPatient.data ?? []).length === 1,
    rawWithPatient.error?.message ?? "");

  // ⚠ THE HALF THE SCHEMA CANNOT ENFORCE. patient_id is NOT NULL, and it is still a plain foreign key to
  // practice_patient, which is global. It can point at another practice's patient, and a certificate
  // about somebody this practice holds no record for is a document about nobody.
  const wrongLink = await createDocument(admin, {
    workspaceId: wsA, patientId: pAlice, title: "HARNESS wrong-practice patient", body: "Body.", ...base,
  });
  const wrongId = (wrongLink as any).data.id;
  const repointed = await admin.from("practice_clinical_document")
    .update({ patient_id: pOther }).eq("id", wrongId).select("id");
  ok("3-setup. the fixture really was repointed at another practice's patient",
    !repointed.error && (repointed.data ?? []).length === 1, repointed.error?.message ?? "");

  await transitionDocument(admin, { workspaceId: wsA, documentId: wrongId, to: "FINAL", ...base });
  const signWrong = await signDocument(admin, aCtx, {
    documentId: wrongId, attestationVersion: DOC_ATTESTATION.version, correlationId: CID,
  });
  ok("3b. ⚠ SIGNING is refused when the patient link does not resolve inside this practice",
    !signWrong.ok && (signWrong as any).code === "PATIENT_LINK_MISSING",
    signWrong.ok ? "was allowed" : (signWrong as any).code);

  // Force it signed by the low-level engine, exactly as a route that skipped Phase 2 would, and prove the
  // rule holds AGAIN at the act it is written about.
  await forceSigned(wsA, wrongId);
  const issueWrong = await issueDocument(admin, aCtx, {
    documentId: wrongId, channel: "printed", recipient: "somebody", correlationId: CID,
  });
  ok("3c. ⚠ ISSUING is refused for the same document, even though it reached SIGNED by another path",
    !issueWrong.ok && (issueWrong as any).code === "PATIENT_LINK_MISSING",
    issueWrong.ok ? "was allowed" : (issueWrong as any).code);

  const rightLink = await createDocument(admin, {
    workspaceId: wsA, patientId: pAlice, title: "HARNESS correctly linked", body: "Body.", ...base,
  });
  const rightId = (rightLink as any).data.id;
  await forceSigned(wsA, rightId);
  const issueRight = await issueDocument(admin, aCtx, {
    documentId: rightId, channel: "printed", recipient: "the patient", correlationId: CID,
  });
  ok("3c-control. the IDENTICAL issue on a correctly linked document succeeds, so 3b/3c are the link and not the call",
    issueRight.ok, issueRight.ok ? "" : `${(issueRight as any).code}: ${(issueRight as any).message}`);

  /* ══ 4. s13 -- THE ASSISTANT BOUNDARY (migration 248) ══════════════════════════════════════════ */

  const grants = (role: string) => new Set(seedRows.filter(r => r.role_code === role).map(r => r.capability_code as string));
  ok("4a. ⚠ the practice_assistant role is NOT granted document.sign (s13, migration 248's deliberate omission)",
    !grants("practice_assistant").has("document.sign"), "an assistant could sign as a practitioner");
  ok("4a-control. ...and IS granted document.view and document.author, so 4a is not 'the assistant has nothing'",
    grants("practice_assistant").has("document.view") && grants("practice_assistant").has("document.author"),
    [...grants("practice_assistant")].filter(c => c.startsWith("document")).join(", "));
  ok("4b. and inbox.review is withheld too -- recording that a result arrived is not judging whether it matters",
    !grants("practice_assistant").has("inbox.review") && grants("practice_assistant").has("inbox.record"),
    [...grants("practice_assistant")].filter(c => c.startsWith("inbox")).join(", "));

  await admin.from("practice_membership").insert({
    workspace_id: wsA, user_id: ASSISTANT, role_code: "practice_assistant", status: "active",
  });
  const { data: am } = await admin.from("practice_membership")
    .select("id").eq("workspace_id", wsA).eq("user_id", ASSISTANT).single();
  await admin.from("practice_role_assignment").insert(
    [...grants("practice_assistant")].map(c => ({
      membership_id: am!.id, capability_code: c, source: "role_default",
    })),
  );
  const asstRes = await resolveWorkspaceContext(admin, ASSISTANT, wsA);
  ok("4c-control. a live assistant context resolves, so the two calls below are made by a real caller",
    asstRes.ok, asstRes.ok ? "" : (asstRes as any).reason);

  if (asstRes.ok) {
    const asst = asstRes.ctx;
    const asstDoc = await createDocument(admin, {
      workspaceId: wsA, patientId: pAlice, title: "HARNESS drafted by the assistant", body: "Prepared at the desk.", ...base,
    });
    const asstDocId = (asstDoc as any).data.id;
    await transitionDocument(admin, { workspaceId: wsA, documentId: asstDocId, to: "FINAL", ...base });

    const asstSign = await signDocument(admin, asst, {
      documentId: asstDocId, attestationVersion: DOC_ATTESTATION.version, correlationId: CID,
    });
    ok("4c. ⚠ a LIVE assistant context is refused the SIGNATURE by the engine, not merely by the route",
      !asstSign.ok && (asstSign as any).code === "NOT_PERMITTED_TO_SIGN",
      asstSign.ok ? "AN ASSISTANT SIGNED AS A PRACTITIONER" : (asstSign as any).code);

    const drSign = await signDocument(admin, aCtx, {
      documentId: asstDocId, attestationVersion: DOC_ATTESTATION.version, correlationId: CID,
    });
    ok("4c-control-2. the practitioner signs THE SAME DOCUMENT, so 4c is the caller and not the document",
      drSign.ok, drSign.ok ? "" : `${(drSign as any).code}: ${(drSign as any).message}`);

    const asstIssue = await issueDocument(admin, asst, {
      documentId: asstDocId, channel: "handed_over", recipient: "the patient at the desk", correlationId: CID,
    });
    ok("4d. ⚠ and the SAME assistant CAN issue a copy -- s13's 'share where delegated'. 4c is a signing boundary, not a locked door",
      asstIssue.ok, asstIssue.ok ? "" : `${(asstIssue as any).code}: ${(asstIssue as any).message}`);

    const { data: attRows } = await admin.from("practice_audit_event")
      .select("payload, actor_id").eq("workspace_id", wsA).eq("event_type", "practice.document_attested");
    const asstAtt = ((attRows ?? []) as any[]).find(e => e.payload?.documentId === asstDocId);
    ok("4e. the attestation on that document names the PRACTITIONER as the actor, never the assistant who drafted it",
      asstAtt?.actor_id === USER_A, `${asstAtt?.actor_id}`);
  }

  /* ══ 5. s12/s8 -- AN UNRESOLVED FIELD BLOCKS THE SIGNATURE ═════════════════════════════════════ */

  const tpl = await createTemplate(admin, {
    workspaceId: wsA, code: "harness_p2_letter", title: "HARNESS letter with a date field",
    kind: "referral_letter",
    bodyTemplate: "Dear colleague,\n\nRe: {{patient.name}}, born {{patient.date_of_birth}}.\n\nPlease see them.",
    sections: [], actorId: USER_A, correlationId: CID,
  });
  ok("5-setup. a workspace template naming a field this patient has no value for",
    tpl.ok, tpl.ok ? "" : (tpl as any).message);
  if (tpl.ok) {
    await setTemplateStatus(admin, {
      workspaceId: wsA, templateId: tpl.data.id, status: "published", actorId: USER_A, correlationId: CID,
    } as any);

    const generated = await generateFromTemplate(admin, aCtx, {
      templateId: tpl.data.id, patientId: pNoDob, allowUnresolved: true, correlationId: CID,
    });
    ok("5-setup-2. generating it for the patient with no birth date produces a document",
      generated.ok, generated.ok ? "" : (generated as any).message);

    if (generated.ok) {
      const genId = generated.data.id;
      const { data: genRow } = await admin.from("practice_clinical_document").select("body").eq("id", genId).single();
      const markers = unresolvedMarkers(String(genRow?.body ?? ""));
      ok("5a. document-generation.ts left a VISIBLE marker where the record had no value",
        markers.length === 1 && markers[0].kind === "generated" && markers[0].marker.includes("date_of_birth"),
        JSON.stringify(markers));
      ok("5a-control. ...and the field that DID resolve is gone from the text, so 5a is not 'nothing merged'",
        String(genRow?.body ?? "").includes("HARNESS Grace Apio")
        && !String(genRow?.body ?? "").includes("{{patient.name}}"),
        JSON.stringify(genRow?.body));

      await transitionDocument(admin, { workspaceId: wsA, documentId: genId, to: "FINAL", ...base });
      const signWithHole = await signDocument(admin, aCtx, {
        documentId: genId, attestationVersion: DOC_ATTESTATION.version, correlationId: CID,
      });
      ok("5b. ⚠ signing is REFUSED while the marker is still in the text (s12: block issuing when required fields are unresolved)",
        !signWithHole.ok && (signWithHole as any).code === "UNRESOLVED_FIELDS",
        signWithHole.ok ? "A DOCUMENT WAS SIGNED WITH A HOLE IN IT" : (signWithHole as any).code);
      // ⚠ `undefined === undefined` WAS THE FIRST VERSION OF THIS, AND IT WAS VACUOUS. With the marker
      // scanner disabled, signDocument succeeded (no `message`) and signBlockers found no blocker (no
      // `message`), and the comparison passed LOUDEST exactly when the rule had been removed. The length
      // test is what makes the wrong answer red.
      const panelMessage = signBlockers({
        status: "FINAL", body: String(genRow?.body ?? ""), markers,
      }).find(b => b.code === "UNRESOLVED_FIELDS")?.message;
      ok("5b-control-a. the refusal message is signBlockers()'s own -- ONE function, shared with the sign panel, not two rules that can drift",
        typeof panelMessage === "string" && panelMessage.length > 0
        && (signWithHole as any).message === panelMessage,
        `${JSON.stringify((signWithHole as any).message)} vs ${JSON.stringify(panelMessage)}`);

      const cleaned = String(genRow?.body ?? "").replace(/\[\[[^\]]+\]\]/g, "2 January 1985");
      await admin.from("practice_clinical_document").update({ body: cleaned }).eq("id", genId);
      const signCleaned = await signDocument(admin, aCtx, {
        documentId: genId, attestationVersion: DOC_ATTESTATION.version, correlationId: CID,
      });
      ok("5b-control-b. the IDENTICAL call once the marker is replaced succeeds, so 5b is the hole and not the document",
        signCleaned.ok, signCleaned.ok ? "" : `${(signCleaned as any).code}: ${(signCleaned as any).message}`);
    }
  }

  ok("5c. the scanner tells a GENERATED marker from an UNMERGED one -- two different mistakes",
    JSON.stringify(unresolvedMarkers("a [[x not recorded]] b {{patient.name}} c").map(m => m.kind))
    === JSON.stringify(["generated", "unmerged"]),
    JSON.stringify(unresolvedMarkers("a [[x not recorded]] b {{patient.name}} c")));
  ok("5c-control. ...and finds nothing in ordinary prose, so 5c is not 'everything is a marker'",
    unresolvedMarkers("Dear Dr Okello, please see this patient. Kind regards.").length === 0);

  /* ══ 6. s8 -- THE EDITOR PAYLOAD ═══════════════════════════════════════════════════════════════ */

  const { data: aliceDoc } = await admin.from("practice_clinical_document")
    .select("id, patient_id, encounter_id, template_id, body, status").eq("id", (draftForRaw as any).data.id).single();
  const support = await editorSupport(admin, aCtx, aliceDoc as any);
  ok("6a. the merge panel resolves this patient's real name from the record",
    support.merge.state === "ok"
    && support.merge.value.find(f => f.field === "patient.name")?.value === "HARNESS Alice Nakato",
    JSON.stringify(support.merge.state === "ok" ? support.merge.value.find(f => f.field === "patient.name") : support.merge));

  const { data: noDobDoc } = await admin.from("practice_clinical_document")
    .insert({ workspace_id: wsA, patient_id: pNoDob, title: "HARNESS no-dob draft", body: "Body." })
    .select("id, patient_id, encounter_id, template_id, body, status").single();
  const supportNoDob = await editorSupport(admin, aCtx, noDobDoc as any);
  const dobField = supportNoDob.merge.state === "ok"
    ? supportNoDob.merge.value.find(f => f.field === "patient.date_of_birth") : null;
  const nameField = supportNoDob.merge.state === "ok"
    ? supportNoDob.merge.value.find(f => f.field === "patient.name") : null;
  ok("6b. ⚠ in ONE payload, a field with a value reads `resolved` and a field without reads `empty`",
    dobField?.state === "empty" && dobField?.value === null && nameField?.state === "resolved",
    JSON.stringify([nameField, dobField]));

  // A patient that cannot be resolved in this workspace is NOT thirteen empty fields.
  const { data: orphanDoc } = await admin.from("practice_clinical_document")
    .insert({ workspace_id: wsA, patient_id: pOther, title: "HARNESS orphan draft", body: "Body." })
    .select("id, patient_id, encounter_id, template_id, body, status").single();
  const supportOrphan = await editorSupport(admin, aCtx, orphanDoc as any);
  ok("6c. ⚠ a merge context that could not be built is `unreadable`, NOT a list of empty fields",
    supportOrphan.merge.state === "unreadable" && (supportOrphan.merge as any).detail.length > 0,
    JSON.stringify(supportOrphan.merge));

  ok("6d. a DRAFT reports NOT_READY as a sign blocker -- finishing and signing are two decisions",
    support.blockers.some(b => b.code === "NOT_READY"), JSON.stringify(support.blockers));
  await transitionDocument(admin, { workspaceId: wsA, documentId: (draftForRaw as any).data.id, to: "FINAL", ...base });
  const { data: finalDoc } = await admin.from("practice_clinical_document")
    .select("id, patient_id, encounter_id, template_id, body, status").eq("id", (draftForRaw as any).data.id).single();
  const supportFinal = await editorSupport(admin, aCtx, finalDoc as any);
  ok("6d-control. ...and the SAME document at FINAL has no blockers at all, so 6d is the status and not a constant",
    supportFinal.blockers.length === 0, JSON.stringify(supportFinal.blockers));

  const leaks = functionPaths(supportFinal);
  ok("6e. ⚠ NOTHING IN THE EDITOR PAYLOAD IS A FUNCTION -- it crosses into a client component",
    leaks.length === 0, leaks.join(", "));
  ok("6e-control. ...and the walker really finds one when it is there, so 6e is not a scan that never ran",
    functionPaths({ ...(supportFinal as any), nested: { deep: [{ boom: () => 1 }] } }).length === 1,
    JSON.stringify(functionPaths({ ...(supportFinal as any), nested: { deep: [{ boom: () => 1 }] } })));

  ok("6f. the attestation travels with the payload, so the panel shows the wording the engine will demand",
    supportFinal.attestation.version === DOC_ATTESTATION.version
    && supportFinal.attestation.statement === DOC_ATTESTATION.statement
    && supportFinal.attestation.distinction.length > 0,
    JSON.stringify(supportFinal.attestation.version));

  /* ══ 7. s3 -- SHARED & ISSUED ══════════════════════════════════════════════════════════════════ */

  // Two signed documents, ONE released and one not, read together.
  const willAmend = await createDocument(admin, {
    workspaceId: wsA, patientId: pAlice, title: "HARNESS issued then amended", body: "Version one.", ...base,
  });
  const willAmendId = (willAmend as any).data.id;
  await forceSigned(wsA, willAmendId);
  const relAmend = await issueDocument(admin, aCtx, {
    documentId: willAmendId, channel: "emailed", recipient: "referrer@example.test", correlationId: CID,
  });
  ok("7-setup. a copy is issued of the document that is about to be amended",
    relAmend.ok, relAmend.ok ? "" : (relAmend as any).code);

  const neverIssued = await createDocument(admin, {
    workspaceId: wsA, patientId: pAlice, title: "HARNESS signed, never issued", body: "Nobody holds this.", ...base,
  });
  await forceSigned(wsA, (neverIssued as any).data.id);

  const shared1 = await sharedAndIssued(admin, wsA);
  const issued1 = shared1.issued.state === "ok" ? shared1.issued.value : [];
  const awaiting1 = shared1.awaiting.state === "ok" ? shared1.awaiting.value : [];
  ok("7a. the release register is readable and the issued copy is in it, with channel, recipient and date",
    shared1.issued.state === "ok"
    && issued1.some(r => r.documentId === willAmendId && r.channel === "emailed"
      && r.recipient === "referrer@example.test" && /^\d{4}-\d{2}-\d{2}/.test(r.releasedAt)),
    JSON.stringify(issued1.map(r => [r.title, r.channel, r.recipient])));
  ok("7a-control. ⚠ and the signed document with NO release is in `awaiting` and NOT in `issued`, in the same read",
    awaiting1.some(d => d.id === (neverIssued as any).data.id)
    && !issued1.some(r => r.documentId === (neverIssued as any).data.id),
    `awaiting ${JSON.stringify(awaiting1.map(d => d.title))}`);

  ok("7b. before any amendment, no issued copy is marked out of date",
    issued1.every(r => r.outdatedForHolder === false),
    JSON.stringify(issued1.filter(r => r.outdatedForHolder).map(r => r.title)));

  const amendment = await amendDocument(admin, {
    workspaceId: wsA, documentId: willAmendId, reason: "HARNESS: the dose was wrong", ...base,
  });
  ok("7-setup-2. the issued document is amended into a successor",
    amendment.ok, amendment.ok ? "" : (amendment as any).message);

  const shared2 = await sharedAndIssued(admin, wsA);
  const issued2 = shared2.issued.state === "ok" ? shared2.issued.value : [];
  const outdated = issued2.filter(r => r.outdatedForHolder);
  ok("7c. ⚠ THE ANSWER NOTHING ELSE IN THIS PRODUCT CAN GIVE: the copy already out there is now flagged as superseded",
    outdated.length === 1 && outdated[0].documentId === willAmendId
    && outdated[0].recipient === "referrer@example.test",
    JSON.stringify(issued2.map(r => [r.title, r.outdatedForHolder])));
  ok("7c-control. ...while the other issued copy in the SAME read is not flagged, so 7c is the amendment and not the column",
    issued2.length >= 2 && issued2.some(r => r.documentId === rightId && r.outdatedForHolder === false),
    JSON.stringify(issued2.map(r => [r.title, r.outdatedForHolder])));

  const brokenShared = await sharedAndIssued(admin, "not-a-uuid" as any);
  ok("7d. ⚠ A FAILED READ IS NOT AN EMPTY REGISTER -- both lists report `unreadable`, carrying the database's own words",
    brokenShared.issued.state === "unreadable" && brokenShared.awaiting.state === "unreadable"
    && (brokenShared.issued as any).detail.length > 0,
    JSON.stringify(brokenShared.issued));
  ok("7d-control. ...while the same call over a real workspace is `ok`, so 7d is not 'this is always unreadable'",
    shared2.issued.state === "ok" && shared2.awaiting.state === "ok");

  const sharedB = await sharedAndIssued(admin, wsB);
  const issuedB = sharedB.issued.state === "ok" ? sharedB.issued.value : [];
  ok("7e. workspace B's Shared & Issued holds none of workspace A's releases",
    !issuedB.some(r => r.documentId === willAmendId || r.documentId === rightId),
    JSON.stringify(issuedB.map(r => r.title)));

  const bDoc = await createDocument(admin, {
    workspaceId: wsB, patientId: pOther, title: "HARNESS B's own issued letter", body: "B's text.",
    actorId: USER_B, correlationId: CID,
  });
  await transitionDocument(admin, { workspaceId: wsB, documentId: (bDoc as any).data.id, to: "FINAL", actorId: USER_B, correlationId: CID });
  await transitionDocument(admin, { workspaceId: wsB, documentId: (bDoc as any).data.id, to: "SIGNED", actorId: USER_B, correlationId: CID });
  const bCtxRes = await resolveWorkspaceContext(admin, USER_B, wsB);
  if (bCtxRes.ok) {
    await issueDocument(admin, bCtxRes.ctx, {
      documentId: (bDoc as any).data.id, channel: "printed", recipient: "B's patient", correlationId: CID,
    });
  }
  const sharedB2 = await sharedAndIssued(admin, wsB);
  ok("7e-control. ...and it DOES hold B's own, so 7e is not an empty list agreeing with everything",
    sharedB2.issued.state === "ok"
    && sharedB2.issued.value.some(r => r.documentId === (bDoc as any).data.id),
    JSON.stringify(sharedB2.issued.state === "ok" ? sharedB2.issued.value.map(r => r.title) : sharedB2.issued));

  ok("7f. the tab exists in the workspace's own nav and resolves to a page that exists",
    DOC_TABS.some(t => t.key === "shared" && t.href === "/practice/documents/shared")
    && existsSync(join(process.cwd(), "src", "app", "practice", "(shell)", "documents", "shared", "page.tsx")),
    DOC_TABS.map(t => t.href).join(", "));
  ok("7f-control. every tab in the workspace declares a capability that exists in the live seed",
    DOC_TABS.every(t => t.capability === null || seedSet.has(t.capability)),
    DOC_TABS.filter(t => t.capability && !seedSet.has(t.capability)).map(t => t.capability).join(", "));
  ok("7g. the page states in words that a release is not a delivery, so no reader infers one",
    SHARE_DELIVERY_NOTE.includes("Nothing is sent") && SHARE_DELIVERY_NOTE.includes("no delivery receipt"),
    SHARE_DELIVERY_NOTE);

  /* ══ 8. s6.4 -- RECIPIENT RULES ════════════════════════════════════════════════════════════════ */

  const emailNoRecipient = await issueDocument(admin, aCtx, {
    documentId: rightId, channel: "emailed", recipient: "   ", correlationId: CID,
  });
  ok("8a. ⚠ an EMAILED copy with no address is refused -- the address is the only record of where it went",
    !emailNoRecipient.ok && (emailNoRecipient as any).code === "RECIPIENT_REQUIRED",
    emailNoRecipient.ok ? "was allowed" : (emailNoRecipient as any).code);
  const emailWithRecipient = await issueDocument(admin, aCtx, {
    documentId: rightId, channel: "emailed", recipient: "clinic@example.test", correlationId: CID,
  });
  ok("8a-control. the same call WITH an address succeeds, so 8a is the recipient and not the channel",
    emailWithRecipient.ok, emailWithRecipient.ok ? "" : (emailWithRecipient as any).code);

  const printedNoRecipient = await issueDocument(admin, aCtx, {
    documentId: rightId, channel: "printed", correlationId: CID,
  });
  ok("8b. a PRINTED copy with no recipient is allowed, and WARNS rather than refusing (s6.4: warn if missing)",
    printedNoRecipient.ok && (printedNoRecipient as any).data.warnings.length === 1,
    printedNoRecipient.ok ? JSON.stringify((printedNoRecipient as any).data.warnings) : (printedNoRecipient as any).code);
  const printedWithRecipient = await issueDocument(admin, aCtx, {
    documentId: rightId, channel: "printed", recipient: "the patient", correlationId: CID,
  });
  ok("8b-control. ...and the same call WITH a recipient carries NO warning, so the warning is not constant",
    printedWithRecipient.ok && (printedWithRecipient as any).data.warnings.length === 0,
    printedWithRecipient.ok ? JSON.stringify((printedWithRecipient as any).data.warnings) : (printedWithRecipient as any).code);

  const badChannel = await issueDocument(admin, aCtx, {
    documentId: rightId, channel: "carrier_pigeon", correlationId: CID,
  });
  // ⚠ THE MESSAGE, NOT JUST THE CODE. The release table's own CHECK constraint would also reject
  // "carrier_pigeon", so a test that only looked at the refusal would stay green with the engine's check
  // deleted -- the database would be quietly doing the work and nobody would know until a route reached
  // the table by another path. The engine's refusal NAMES THE ALLOWED CHANNELS; Postgres's does not.
  ok("8c. a channel the release register has no value for is refused BY THE ENGINE, which says which ones exist",
    !badChannel.ok && (badChannel as any).code === "VALIDATION_ERROR"
    && /how it was issued must be one of/.test((badChannel as any).message),
    badChannel.ok ? "was allowed" : (badChannel as any).message);
  const channelResults: string[] = [];
  for (const [code] of RELEASE_CHANNELS) {
    const r = await issueDocument(admin, aCtx, {
      documentId: rightId, channel: code, recipient: "a named recipient", correlationId: CID,
    });
    if (!r.ok) channelResults.push(`${code}: ${(r as any).code}`);
  }
  ok("8c-control. ...while EVERY declared channel is accepted, so 8c is the value and not the check",
    channelResults.length === 0, channelResults.join(", "));
  ok("8d. every channel that REQUIRES a recipient is a channel that exists",
    (RECIPIENT_REQUIRED_CHANNELS as readonly string[])
      .every(c => RELEASE_CHANNELS.some(([code]) => code === c))
    && RECIPIENT_REQUIRED_CHANNELS.length > 0,
    RECIPIENT_REQUIRED_CHANNELS.join(", "));

  /* ══ 9. s17 -- ONLY A SIGNED DOCUMENT MAY BE ISSUED ════════════════════════════════════════════ */

  const draftIssue = await createDocument(admin, {
    workspaceId: wsA, patientId: pAlice, title: "HARNESS draft nobody may issue", body: "Draft.", ...base,
  });
  const draftIssueId = (draftIssue as any).data.id;
  const issueDraft = await issueDocument(admin, aCtx, {
    documentId: draftIssueId, channel: "printed", recipient: "somebody", correlationId: CID,
  });
  // ⚠ AGAIN THE MESSAGE. recordRelease() in documentation.ts refuses an unsigned document too, so a
  // code-only check would stay green with issueDocument's own check removed -- and the rule would then be
  // one layer deeper than this harness claimed, which is exactly the sort of drift that is discovered
  // during an incident. The wording below belongs to issueDocument and to nothing else.
  ok("9a. ⚠ a DRAFT cannot be issued -- that is how somebody ends up holding a letter nobody stood behind",
    !issueDraft.ok && (issueDraft as any).code === "NOT_SIGNED"
    && /issuing a draft is how somebody ends up/.test((issueDraft as any).message),
    issueDraft.ok ? "was allowed" : (issueDraft as any).message);
  await forceSigned(wsA, draftIssueId);
  const issueSigned = await issueDocument(admin, aCtx, {
    documentId: draftIssueId, channel: "printed", recipient: "somebody", correlationId: CID,
  });
  ok("9a-control. the SAME document once signed can be issued, so 9a is the status and not the call",
    issueSigned.ok, issueSigned.ok ? "" : (issueSigned as any).code);

  const issueSuperseded = await issueDocument(admin, aCtx, {
    documentId: willAmendId, channel: "printed", recipient: "somebody", correlationId: CID,
  });
  ok("9b. ⚠ a SUPERSEDED version cannot be issued, and the refusal names the current one",
    !issueSuperseded.ok && (issueSuperseded as any).code === "NOT_SIGNED"
    && /amended/.test((issueSuperseded as any).message),
    issueSuperseded.ok ? "was allowed" : (issueSuperseded as any).message);
  if (amendment.ok) {
    await forceSigned(wsA, amendment.data.id);
    const issueSuccessor = await issueDocument(admin, aCtx, {
      documentId: amendment.data.id, channel: "printed", recipient: "somebody", correlationId: CID,
    });
    ok("9b-control. ...and the SUCCESSOR, once signed, can be -- so 9b is the supersession and not the chain",
      issueSuccessor.ok, issueSuccessor.ok ? "" : (issueSuccessor as any).code);
  }

  /* ══ 10. THE CLIENT/SERVER BOUNDARY, READ FROM THE SOURCE ══════════════════════════════════════ */

  const consolePath = join(process.cwd(), "src", "app", "practice", "(shell)", "documents", "[documentId]", "DocumentConsole.tsx");
  ok("10-setup. the editor component is where this check thinks it is", existsSync(consolePath), consolePath);
  const consoleSrc = readFileSync(consolePath, "utf8");
  const serverImports = [
    "documents-workspace-issue", "documents-workspace\"", "/documentation\"", "/provisioning",
    "/supabase/server", "node:crypto",
  ].filter(m => consoleSrc.includes(`from "@/lib/practice/${m}`) || consoleSrc.includes(`from "${m}"`));
  ok("10a. ⚠ the editor imports NOTHING that reaches the Supabase server client",
    serverImports.length === 0, serverImports.join(", "));
  ok("10a-control. ...and it DOES import the constants module, so 10a is reading the right file",
    consoleSrc.includes("documents-workspace-constants") && consoleSrc.includes("\"use client\""),
    "the scan found neither the import nor the directive");

  const constantsSrc = readFileSync(
    join(process.cwd(), "src", "lib", "practice", "documents-workspace-constants.ts"), "utf8");
  const runtimeImports = constantsSrc.split("\n")
    .filter(l => /^\s*import\s/.test(l) && !/^\s*import\s+type\s/.test(l));
  ok("10b. ⚠ the constants module has NO runtime imports at all, which is the property that makes it safe to share",
    runtimeImports.length === 0, runtimeImports.join(" | "));

  await cleanup();
  return report();
}

function report() {
  console.log(`\n${fails.length === 0 ? "PASSED" : "FAILED"}  ${pass} passed, ${fails.length} failed`);
  if (fails.length) { for (const f of fails) console.log(`   - ${f}`); process.exit(1); }
  process.exit(0);
}

main().catch(async e => {
  console.error(e);
  await cleanup().catch(() => {});
  process.exit(1);
});
