import { createClient, createAdminClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import { loadMyShift } from "@/lib/hww/my-shift";
import { titleCase, fmtTime, fmtWhen, StatCard, SectionCard, Empty, Chip, ewsColor } from "@/lib/hww/kit";
import RecordObs from "./RecordObs";

// Observations & PEWS (HWW-WARD-001 S5 / HWW-OBS-001) — the nurse's
// observation surface over op_observations: the due/overdue queue for my
// patients (complete a due row in place), per-patient PEWS trend from real
// recorded scores, and ad-hoc recording. EWS >= 5 or a concern flag
// auto-escalates via the existing engine; observation schedules are generated
// by coordinators (acuity-based frequencies live in ward configuration).
/* eslint-disable @typescript-eslint/no-explicit-any */

export const dynamic = "force-dynamic";

export default async function ObservationsPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");
  const admin = createAdminClient();
  const data = await loadMyShift(admin, user.id);
  const { patients, observations } = data;

  const due = observations.filter((o: any) => ["due", "overdue"].includes(o.status))
    .sort((a: any, b: any) => (a.status === "overdue" ? 0 : 1) - (b.status === "overdue" ? 0 : 1) || +new Date(a.due_at ?? 0) - +new Date(b.due_at ?? 0));
  const recorded = observations.filter((o: any) => o.status === "recorded")
    .sort((a: any, b: any) => +new Date(b.recorded_at ?? 0) - +new Date(a.recorded_at ?? 0));
  const overdueCount = due.filter((o: any) => o.status === "overdue").length;
  const escalated24h = recorded.filter((o: any) => o.escalation_triggered).length;

  const trend = (pid: string) => recorded
    .filter((o: any) => o.patient_id === pid && o.ews_score != null)
    .slice(0, 6).reverse().map((o: any) => o.ews_score as number);
  const latestEws = (pid: string) => { const t = trend(pid); return t.length ? t[t.length - 1] : null; };

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Observations &amp; PEWS</h1>
        <p className="text-sm text-gray-500 mt-1">Your observation queue and deterioration picture. PEWS ≥ 5 or a concern flag escalates automatically.</p>
      </div>

      <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">
        <StatCard icon="📈" title="Due Now" value={due.length - overdueCount} sub="scheduled observations" />
        <StatCard icon="🔴" title="Overdue" value={overdueCount} tone={overdueCount > 0 ? "text-red-600" : undefined} sub="past their due time" />
        <StatCard icon="🚨" title="Auto-Escalated" value={escalated24h} tone={escalated24h > 0 ? "text-orange-600" : undefined} sub="from recorded observations" />
        <StatCard icon="🧑‍⚕️" title="Watched Patients" value={patients.length} sub="my active assignment" />
      </div>

      <SectionCard icon="⏰" title="Due Queue" count={due.length}>
        {due.length === 0 ? (
          <Empty>Nothing due. Observation schedules are generated by your coordinator from ward configuration (frequency by acuity level).</Empty>
        ) : (
          <div className="divide-y divide-gray-100">
            {due.map((o: any) => (
              <div key={o.id} className="py-2.5">
                <div className="flex flex-wrap items-center gap-2">
                  <span className={`text-xs tabular-nums w-14 ${o.status === "overdue" ? "text-red-600 font-semibold" : "text-gray-500"}`}>{o.status === "overdue" ? "OVERDUE" : fmtTime(o.due_at)}</span>
                  <span className="font-medium text-gray-800">{o.op_patients?.label ?? "Patient"}</span>
                  <Chip tone="bg-gray-100 text-gray-600">{titleCase(o.observation_type)}</Chip>
                  {o.status === "overdue" && <Chip tone="bg-red-100 text-red-700">Overdue</Chip>}
                  <span className="ml-auto" />
                  <RecordObs patientId={o.patient_id} patientLabel={o.op_patients?.label ?? "patient"} observationId={o.id} defaultType={o.observation_type} compact />
                </div>
              </div>
            ))}
          </div>
        )}
      </SectionCard>

      <SectionCard icon="📊" title="PEWS Trends — My Patients" count={patients.length}>
        {patients.length === 0 ? <Empty>No active patient assignments.</Empty> : (
          <div className="divide-y divide-gray-100">
            {patients.map((a: any) => {
              const p = a.op_patients;
              const t = trend(p.id);
              const cur = latestEws(p.id);
              return (
                <div key={p.id} className="py-2.5">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="font-medium text-gray-800">{p.label}</span>
                    {p.op_beds?.label && <span className="text-xs text-gray-400">{p.op_beds.label}</span>}
                    <span className={`font-bold tabular-nums ${ewsColor(cur)}`}>{cur ?? "—"}</span>
                    {t.length > 1 && (
                      <span className="text-xs text-gray-400 tabular-nums">trend: {t.join(" → ")}</span>
                    )}
                    {cur != null && cur >= 5 && <Chip tone="bg-red-100 text-red-700">At threshold</Chip>}
                    <span className="ml-auto" />
                    <RecordObs patientId={p.id} patientLabel={p.label} compact={false} />
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </SectionCard>

      <SectionCard icon="📝" title="Recently Recorded" count={Math.min(recorded.length, 12)}>
        {recorded.length === 0 ? <Empty>No recorded observations yet for your patients.</Empty> : (
          <div className="divide-y divide-gray-50">
            {recorded.slice(0, 12).map((o: any) => (
              <div key={o.id} className="py-2 flex items-center gap-2 text-sm">
                <span className="text-xs text-gray-400 tabular-nums w-24 shrink-0">{fmtWhen(o.recorded_at)}</span>
                <span className="text-gray-700">{o.op_patients?.label}</span>
                <Chip tone="bg-gray-100 text-gray-600">{titleCase(o.observation_type)}</Chip>
                {o.ews_score != null && <span className={`font-semibold tabular-nums ${ewsColor(o.ews_score)}`}>PEWS {o.ews_score}</span>}
                {o.concern && <Chip tone="bg-orange-100 text-orange-700">Concern</Chip>}
                {o.escalation_triggered && <Chip tone="bg-red-100 text-red-700">Escalated</Chip>}
                {(o.findings as any)?.note && <span className="text-xs text-gray-400 truncate">{(o.findings as any).note}</span>}
              </div>
            ))}
          </div>
        )}
      </SectionCard>

      <p className="text-center text-[11px] text-gray-400 pt-1">
        Every recorded observation is a real operational event. A breaching score raises a live escalation to your coordinator with a response deadline.
      </p>
    </div>
  );
}
